import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import ReactQueryProvider from "@/lib/providers/react-query-provider";

export const metadata: Metadata = {
  title: "Jobseeker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <SessionProvider>
          <ReactQueryProvider>
            {" "}
            {children}
            <Toaster
              richColors
              toastOptions={{
                closeButton: true,
              }}
            />
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
